version: '3.4'

services:
  webapi.cleanarchitecture.template:
    image: ${DOCKER_REGISTRY-}webapicleanarchitecturetemplate
    build:
      context: .
      dockerfile: WebAPI.CleanArchitecture.Template/Dockerfile
  
  cleanarchitecture.template.db:
    image: postgres:latest
    container_name: Database
    environment:
      - POSTGRES_DB=CleanArchitectureTemplate-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - "5432:5432"